### ISSUE TITLE
Being able to see the PRs of all projects. (not just one)

### ISSUE THREAD

**Issue by srigaux** [cribeiro84/azure-devops-pull-request-hub#100]
It would be great if we can show all the PullRequest of all the DevOps projects when we clear the "Projects" filter.

**Comment by cribeiro84** [comment]
Thanks for the feedback @srigaux - We totally agree with the request but there is a limitation for doing this approach because the current APIs does not support multiple projects as filter making it difficult to control the number of PRs that could be shown, depending of the setup the loading process also can be heavily impacted. Therefore, we decided at this moment not support this feature.
