### ISSUE TITLE
After the automatic update, I can no longer use it

### ISSUE THREAD

**Issue by arashazhdary** [cribeiro84/azure-devops-pull-request-hub#113]
There was an error during the extension load: TFS.WebApi.Exception: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1.

Please help me

**Comment by cribeiro84** [comment]
Hello @arashazhdary - sorry about that. We did some components upgrades on the extension to support new features.
are you using Azure DevOps Cloud or the Server?

**Comment by arashazhdary** [comment]
dedicated server
Azure Devops 2019 Version 1.1

**Comment by purduekenny** [comment]
I receive the same message. The error message places the blame in my court, but I'm not sure how to update the REST API version to support the new async feature you included in the update. Any direction would be appreciated!

**Comment by cazofeifacr** [comment]
There was an error during the extension load: TFS.WebApi.Exception: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1.

**Comment by hwoodward2019** [comment]
As of 7/15/2020, We are still experiencing the same issue regarding "TFS.WebApi.Exception: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1."

I see in your notes, that you are downgrading the API due to Azure DevOps server issues. Is this still happening? I seen that an update was pushed yesterday and the team is still receiving the error. Any update would be appreciated, I assuming you are still working the issue and I am just being impatient :) On a side note, thank you for your hard work!
