### ISSUE TITLE
DevOps Server not recognized

### ISSUE THREAD

**Issue by arminNadarevic** [cribeiro84/azure-devops-pull-request-hub#57]
The code that checks is it is Cloud or Server dose not work by type because we have a Self hosted Server and it returns 4 as type. I am not sure that 4 is Cloud. 

 private async getOrganizationBaseUrl() {
    const url = new URL(document.referrer);
    if (DevOps.getHost().type != 4) { //4 - Azure DevOps Cloud
      const collectionName = url.pathname.split('/')[2];
      this.baseUrl = `${url.origin}/tfs/${collectionName}/`;
    }
    else { .... }

**Comment by cribeiro84** [comment]
@arminNadarevic thanks a lot for the information! I'm working on it to check how to solve it. The docs of Microsoft has the host type information but it seems it does not work as expected. I created my self-hosted Azure DevOps instance to try that out and debug it. Hopefully it will be fixed in the following days.

I will be closing this issue once it's related to #45

**Comment by cribeiro84** [comment]
@arminNadarevic I released a new version with this fix. Would you mind to test it again?

Thanks a lot

**Comment by arminNadarevic** [comment]
Hi just want to say that it works now.

Den mån 16 dec. 2019 12:49Carlos Alessandro Ribeiro <
notifications@github.com> skrev:

**Comment by cribeiro84** [comment]
Excelent! Thanks a lot for your feedback... :-)

**Comment by cribeiro84** [comment]
Also, if you don't mind, please give your rate about this extension. :-)
https://marketplace.visualstudio.com/items?itemName=caribeiro84.pull-request-manager-hub&ssr=false#review-details
