### ISSUE TITLE
View completed pull requests via filters

### ISSUE THREAD

**Issue by leemorton** [cribeiro84/azure-devops-pull-request-hub#64]
This is a great extension, would love to be able to view completed pull requests via the filters also though. So that I can see the latest contributions from a whole department perspective.

**Comment by cribeiro84** [comment]
@leemorton thanks for your feedback and suggestion. At this moment I don't have it in the roadmap because it will change the main focus of this extension which is to facilitate to manage active pull requests and it would impact on the overall performance to manage multiple API calls per project, per repository.

**Comment by cribeiro84** [comment]
we are working on this feature in this #131 open issue.
