### ISSUE TITLE
Unable to publish extension due to: - Incompatible API version(5.1)

### ISSUE THREAD

**Issue by KasperjuulLarsen** [cribeiro84/azure-devops-pull-request-hub#88]
Hi,
We are using Azure Devops Server version 2019 (17.143.28621.4) REST Api 5.0. Why am I seing this error when trying to install extension?
BR
Kasper

**Comment by cribeiro84** [comment]
@KasperjuulLarsen sorry for hearing that you are not able to install the extension. We had to upgrade the API version to 5.1 in order to being able to integrate with new APIs and features.
I believe you are running the Azure DevOps Server, right? If so, one workaround I would suggest you to do is to fork our repo and publish a custom extension for you with the previous version that supports yet the API 5.0 only.

Would that be feasible for you?

Thank you
